name: SocialBlueprint
author: Dasannn
main: com.dasannn.socialblueprint.SocialBlueprintPlugin
version: 1.0
description: Social layer plugin for Paper
api-version: '26.3'

libraries:
  - org.xerial:sqlite-jdbc:3.53.4.0
